on:
  push:
    branches:
      - main
    pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build only
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: neeldug/neeldug.github.io
